apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniapp-fastapi
  template:
    metadata:
      labels:
        app: miniapp-fastapi
    spec:
      containers:
      - name: miniapp-fastapi
        image: ghcr.io/Andri-RJ/miniapp-fastapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: miniapp-fastapi
spec:
  selector:
    app: miniapp-fastapi
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
